// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Report struct {
	ID                    pgtype.UUID        `json:"id"`
	ReportName            string             `json:"report_name"`
	ReportType            string             `json:"report_type"`
	TemplateID            pgtype.UUID        `json:"template_id"`
	Topic                 string             `json:"topic"`
	Specialty             pgtype.Text        `json:"specialty"`
	PlantOrBusinessObject pgtype.Text        `json:"plant_or_business_object"`
	ReportYear            pgtype.Int4        `json:"report_year"`
	Status                string             `json:"status"`
	ExtraContextJson      []byte             `json:"extra_context_json"`
	CreatorID             pgtype.Text        `json:"creator_id"`
	CreatorName           pgtype.Text        `json:"creator_name"`
	Source                string             `json:"source"`
	LatestJobID           pgtype.UUID        `json:"latest_job_id"`
	LatestReportFileID    pgtype.UUID        `json:"latest_report_file_id"`
	GeneratedAt           pgtype.Timestamptz `json:"generated_at"`
	ExportedAt            pgtype.Timestamptz `json:"exported_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type ReportEvent struct {
	ID          pgtype.UUID        `json:"id"`
	ReportID    pgtype.UUID        `json:"report_id"`
	JobID       pgtype.UUID        `json:"job_id"`
	EventType   string             `json:"event_type"`
	Message     pgtype.Text        `json:"message"`
	PayloadJson []byte             `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReportFile struct {
	ID         pgtype.UUID        `json:"id"`
	ReportID   pgtype.UUID        `json:"report_id"`
	JobID      pgtype.UUID        `json:"job_id"`
	Filename   string             `json:"filename"`
	FileType   string             `json:"file_type"`
	FileRef    pgtype.Text        `json:"file_ref"`
	FileSize   int64              `json:"file_size"`
	FileStatus string             `json:"file_status"`
	CreatedBy  pgtype.Text        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ReportJob struct {
	ID                  pgtype.UUID        `json:"id"`
	RequestID           pgtype.Text        `json:"request_id"`
	Source              string             `json:"source"`
	JobType             string             `json:"job_type"`
	TargetType          string             `json:"target_type"`
	TargetID            string             `json:"target_id"`
	AsynqTaskID         pgtype.Text        `json:"asynq_task_id"`
	QueueName           string             `json:"queue_name"`
	ReportID            pgtype.UUID        `json:"report_id"`
	TemplateID          pgtype.UUID        `json:"template_id"`
	RequestPayloadJson  []byte             `json:"request_payload_json"`
	ResponsePayloadJson []byte             `json:"response_payload_json"`
	InputSnapshotJson   []byte             `json:"input_snapshot_json"`
	Status              string             `json:"status"`
	ProgressJson        []byte             `json:"progress_json"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	RetryCount          int32              `json:"retry_count"`
	MaxAttempts         int32              `json:"max_attempts"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ReportJobAttempt struct {
	ID                 pgtype.UUID        `json:"id"`
	JobID              pgtype.UUID        `json:"job_id"`
	AttemptNumber      int32              `json:"attempt_number"`
	AsynqTaskID        pgtype.Text        `json:"asynq_task_id"`
	TriggerSource      string             `json:"trigger_source"`
	Reason             pgtype.Text        `json:"reason"`
	RequestPayloadJson []byte             `json:"request_payload_json"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ReportMaterial struct {
	ID           pgtype.UUID        `json:"id"`
	MaterialName string             `json:"material_name"`
	MaterialType string             `json:"material_type"`
	Category     pgtype.Text        `json:"category"`
	FileRef      pgtype.Text        `json:"file_ref"`
	Filename     string             `json:"filename"`
	FileSize     int64              `json:"file_size"`
	Description  pgtype.Text        `json:"description"`
	TagsJson     []byte             `json:"tags_json"`
	Enabled      bool               `json:"enabled"`
	CreatedBy    pgtype.Text        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type ReportOperationLog struct {
	ID                   pgtype.UUID        `json:"id"`
	OperatorID           pgtype.Text        `json:"operator_id"`
	OperatorName         pgtype.Text        `json:"operator_name"`
	OperationType        string             `json:"operation_type"`
	TargetType           string             `json:"target_type"`
	TargetID             string             `json:"target_id"`
	RequestID            pgtype.Text        `json:"request_id"`
	RequestSource        pgtype.Text        `json:"request_source"`
	ToolName             pgtype.Text        `json:"tool_name"`
	ParameterSummaryJson []byte             `json:"parameter_summary_json"`
	OperationResult      string             `json:"operation_result"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	MetadataJson         []byte             `json:"metadata_json"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ReportOutline struct {
	ID           pgtype.UUID        `json:"id"`
	ReportID     pgtype.UUID        `json:"report_id"`
	OutlineJson  []byte             `json:"outline_json"`
	Version      int32              `json:"version"`
	Source       string             `json:"source"`
	SourceJobID  pgtype.UUID        `json:"source_job_id"`
	IsCurrent    bool               `json:"is_current"`
	ManualEdited bool               `json:"manual_edited"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ReportSection struct {
	ID               pgtype.UUID        `json:"id"`
	ReportID         pgtype.UUID        `json:"report_id"`
	OutlineID        pgtype.UUID        `json:"outline_id"`
	ParentID         pgtype.UUID        `json:"parent_id"`
	OutlineNodeID    pgtype.Text        `json:"outline_node_id"`
	SectionPath      string             `json:"section_path"`
	Title            string             `json:"title"`
	Level            int32              `json:"level"`
	SortOrder        int32              `json:"sort_order"`
	Numbering        pgtype.Text        `json:"numbering"`
	SectionType      string             `json:"section_type"`
	Content          string             `json:"content"`
	TablesJson       []byte             `json:"tables_json"`
	ImagesJson       []byte             `json:"images_json"`
	GenerationStatus string             `json:"generation_status"`
	ContentSource    string             `json:"content_source"`
	ManualEdited     bool               `json:"manual_edited"`
	Version          int32              `json:"version"`
	LastJobID        pgtype.UUID        `json:"last_job_id"`
	GeneratedAt      pgtype.Timestamptz `json:"generated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ReportSectionVersion struct {
	ID           pgtype.UUID        `json:"id"`
	ReportID     pgtype.UUID        `json:"report_id"`
	SectionID    pgtype.UUID        `json:"section_id"`
	Version      int32              `json:"version"`
	Source       string             `json:"source"`
	Content      string             `json:"content"`
	TablesJson   []byte             `json:"tables_json"`
	JobID        pgtype.UUID        `json:"job_id"`
	Requirements pgtype.Text        `json:"requirements"`
	CreatedBy    pgtype.Text        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ReportSetting struct {
	ID                   string             `json:"id"`
	LlmJson              []byte             `json:"llm_json"`
	DefaultTemplatesJson []byte             `json:"default_templates_json"`
	FileJson             []byte             `json:"file_json"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ReportTemplate struct {
	ID              pgtype.UUID        `json:"id"`
	TemplateName    string             `json:"template_name"`
	ReportType      string             `json:"report_type"`
	Version         int32              `json:"version"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Filename        string             `json:"filename"`
	FileSize        int64              `json:"file_size"`
	StructureJson   []byte             `json:"structure_json"`
	StyleConfigJson []byte             `json:"style_config_json"`
	Description     pgtype.Text        `json:"description"`
	Enabled         bool               `json:"enabled"`
	CreatedBy       pgtype.Text        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ReportTemplateMaterial struct {
	ID         pgtype.UUID        `json:"id"`
	TemplateID pgtype.UUID        `json:"template_id"`
	MaterialID pgtype.UUID        `json:"material_id"`
	UsageType  string             `json:"usage_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ReportType struct {
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	Enabled           bool               `json:"enabled"`
	DefaultTemplateID pgtype.UUID        `json:"default_template_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
